
[[constraint]]
  name = "github.com/jmoiron/sqlx"
  version = "^1.2.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "~1.0.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/jmespath/go-jmespath"
  version = "0.2.2"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.22"

[[constraint]]
  name = "github.com/evanphx/json-patch"
  version = "4.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/dop251/goja"
