
[[constraint]]
  name = "github.com/jmoiron/sqlx"
  version = "^1.2.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.3.0"

[prune]
  go-tests = true
  unused-packages = true
