
[[constraint]]
  name = "github.com/jmoiron/sqlx"
  version = "^1.2.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.3.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/jmespath/go-jmespath"
  version = "0.2.2"

[[constraint]]
  name = "github.com/tidwall/gjson"
  version = "1.1.5"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "1.8.22"
